models.py
from app import db

class test1(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30))
    email = db.Column(db.String(30))
    number = db.Column(db.Integer)

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)

    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite3'

    db.init_app(app)

    from views import main
    app.register_blueprint(main)

    app.config["DEBUG"]=True

    return app

views.py
from flask import Blueprint, render_template, request, redirect, url_for
from app import db
from models import test1

main = Blueprint('main', __name__)

@main.route('/')
def index():
    datas = test1.query.all()
    return render_template('index.html', datas=datas)

@main.route('/sign')
def sign():
    return render_template('sign.html')

@main.route('/sign', methods=['POST'])
def sign_post():
    name = request.form.get('name')
    email = request.form.get('email')
    number = request.form.get('number')

    new_data = test1(name=name, email=email, number=number)
    db.session.add(new_data)
    db.session.commit()

    return redirect(url_for('main.index'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet"> 
    
    {% block css %}{% endblock %}

  </head>

  <body>
    {% block body %}{% endblock %}
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}SIMPLE TEST{% endblock %}

{% block css %}
<!-- Bootstrap theme -->
<link href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="{{ url_for('static', filename='css/theme.css') }}" rel="stylesheet">
{% endblock %}

{% block body %}
<div class="container theme-showcase" role="main">

    <div class="jumbotron">
        <h1>SIMPLE TEST</h1>
        <a type="button" class="btn btn-link" href="{{ url_for('main.sign') }}">CLICK TO INPUT</a>
    </div>

    {% for data in datas %}
    <div class="page-header">
        <h1>{{ data.name }}</h1>
    </div>
    <div class="well">
        <p>{{ data.email }}</p>
    </div>
    <div class="well">
        <p>{{ data.number }}</p>
    </div>
    {% endfor %}

</div> <!-- /container -->
{% endblock %}

templates/sign.html
{% extends 'base.html' %}

{% block title %}SIMPLE TEST INPUT{% endblock %}

{% block css %}
<!-- Custom styles for this template -->
<link href="{{ url_for('static', filename='css/sign.css') }}" rel="stylesheet">
{% endblock %}

{% block body %}
<div class="container">

    <form class="form-signin" method="POST" action="{{ url_for('main.sign_post') }}">
        <h2 class="form-signin-heading">SIMPLE INPUT</h2>
        <div class="form-group">
            <label for="inputName" class="sr-only">Name</label>
            <input type="text" id="inputName" name="name" class="form-control" placeholder="Name" required autofocus>
        </div>
        <div class="form-group">
            <label for="inputEmail" class="sr-only">Email</label>
            <input type="text" id="inputEmail" name="email" class="form-control" placeholder="Email" required autofocus>
        </div>
        <div class="form-group">
            <label for="number" class="sr-only">Number</label>
            <textarea class="form-control" name="number" id="number" placeholder="Number"
                required></textarea>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">ADD</button>
    </form>

</div> <!-- /container -->
{% endblock %}